/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BelajarLogin;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Ichan
 */
public class AplikasiSederhana extends javax.swing.JFrame {
public Connection start;

    /**
     * Creates new form AplikasiSederhana
     */
    public AplikasiSederhana() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void network(){
        try{
            start=DriverManager.getConnection("jdbc:mysql://localhost:3306/latihan_login","root","");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Koneksi Failed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        Laki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        Agama = new javax.swing.JComboBox();
        bola = new javax.swing.JCheckBox();
        futsal = new javax.swing.JCheckBox();
        basket = new javax.swing.JCheckBox();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Nama");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Agama");

        jLabel8.setText("Hobi");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Laki);
        Laki.setText("Laki - Laki");

        buttonGroup1.add(Perempuan);
        Perempuan.setText("Perempuan");
        Perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerempuanActionPerformed(evt);
            }
        });

        Agama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISLAM", "KRISTEN", "HINDU", "BUDHA" }));
        Agama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgamaActionPerformed(evt);
            }
        });

        buttonGroup2.add(bola);
        bola.setText("Sepak Bola");

        buttonGroup2.add(futsal);
        futsal.setText("Futsal");

        buttonGroup2.add(basket);
        basket.setText("Basket");
        basket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProsesMouseClicked(evt);
            }
        });
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        tabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        tabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabel.setForeground(new java.awt.Color(102, 102, 102));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Jenis Kelamin", "Agama", "Hobi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basket)
                            .addComponent(futsal)
                            .addComponent(Agama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Laki)
                            .addComponent(Perempuan)
                            .addComponent(bola, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProses))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Laki))
                        .addGap(34, 34, 34))
                    .addComponent(Perempuan))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(futsal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(basket)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void PerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerempuanActionPerformed

    private void AgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgamaActionPerformed

    private void basketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basketActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        if(Laki.isSelected()){
            if(bola.isSelected()){
                try {
                    network();
                        String sql=("insert into data (nama, jk, agama, hobi) VALUES"
                                +"('"+txtNama.getText()+"','"+Laki.getText()+"','"+Agama.getSelectedItem()
                                +"','"+"Bola"+"')");
                        Statement stat = start.createStatement();
                        stat.executeUpdate(sql);
                                 JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
                     }catch(HeadlessException t){
                         JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN");
                    }   catch (SQLException ex) {
                                 Logger.getLogger(AplikasiSederhana.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }else if(futsal.isSelected()){
                try {
                network();
                    String sql=("insert into data (nama, jk, agama, hobi) VALUES"
                            +"('"+txtNama.getText()+"','"+Laki.getText()+"','"+Agama.getSelectedItem()
                            +"','"+"Futsal"+"')");
                    Statement stat = start.createStatement();
                    stat.executeUpdate(sql);
                             JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
                 }catch(HeadlessException t){
                     JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN");
            }   catch (SQLException ex) {
                         Logger.getLogger(AplikasiSederhana.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(basket.isSelected()){
                try {
                network();
                    String sql=("insert into data (nama, jk, agama, hobi) VALUES"
                            +"('"+txtNama.getText()+"','"+Laki.getText()+"','"+Agama.getSelectedItem()
                            +"','"+"Basket"+"')");
                    Statement stat = start.createStatement();
                    stat.executeUpdate(sql);
                             JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
                 }catch(HeadlessException t){
                     JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN");
                }   catch (SQLException ex) {
                             Logger.getLogger(AplikasiSederhana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else if(Perempuan.isSelected()){
            if(bola.isSelected()){
                try {
                    network();
                        String sql=("insert into data (nama, jk, agama, hobi) VALUES"
                                +"('"+txtNama.getText()+"','"+Perempuan.getText()+"','"+Agama.getSelectedItem()
                                +"','"+"Bola"+"')");
                        Statement stat = start.createStatement();
                        stat.executeUpdate(sql);
                                 JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
                     }catch(HeadlessException t){
                         JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN");
                    }   catch (SQLException ex) {
                                 Logger.getLogger(AplikasiSederhana.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }else if(futsal.isSelected()){
                try {
                network();
                    String sql=("insert into data (nama, jk, agama, hobi) VALUES"
                            +"('"+txtNama.getText()+"','"+Perempuan.getText()+"','"+Agama.getSelectedItem()
                            +"','"+"Futsal"+"')");
                    Statement stat = start.createStatement();
                    stat.executeUpdate(sql);
                             JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
                 }catch(HeadlessException t){
                     JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN");
            }   catch (SQLException ex) {
                         Logger.getLogger(AplikasiSederhana.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(basket.isSelected()){
                try {
                network();
                    String sql=("insert into data (nama, jk, agama, hobi) VALUES"
                            +"('"+txtNama.getText()+"','"+Perempuan.getText()+"','"+Agama.getSelectedItem()
                            +"','"+"Basket"+"')");
                    Statement stat = start.createStatement();
                    stat.executeUpdate(sql);
                             JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
                 }catch(HeadlessException t){
                     JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN");
                }   catch (SQLException ex) {
                             Logger.getLogger(AplikasiSederhana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        try{
            network();
            String sql=("SELECT *FROM data;");
            Statement stat= start.createStatement();
            ResultSet res=stat.executeQuery(sql);
                
                DefaultTableModel model = (DefaultTableModel)tabel.getModel();
                int hapus=tabel.getRowCount();
                for(int i=0 ;i< hapus; i++){
                    model.removeRow(0);
                }
                while(res.next()){
                    Object[] obj= new Object[4];
                    obj[0]=res.getString("nama");
                    obj[1]=res.getString("jk");
                    obj[2]=res.getString("agama");
                    obj[3]=res.getString("hobi");
                    
                    model.addRow(obj);
                }
            }catch(HeadlessException t){
 
            } catch (SQLException ex) {
        Logger.getLogger(AplikasiSederhana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void btnProsesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProsesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProsesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Agama;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JCheckBox basket;
    private javax.swing.JCheckBox bola;
    private javax.swing.JButton btnProses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox futsal;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
